import numpy as np
import tensorflow as tf
import os

os.chdir(r'D:\CTAIML FINAL WORK')

# ── Load trained model ────────────────────────────────────────
model      = tf.keras.models.load_model('autoencoder_model.keras')
X_scaled   = np.load('X_scaled.npy')
threshold  = np.load('threshold_95.npy')[0]
scaler_mean  = np.load('scaler_mean.npy')
scaler_scale = np.load('scaler_scale.npy')

print(f"Model loaded ✓")
print(f"Anomaly threshold : {threshold:.6f}")

# ── Convert to TFLite INT8 ────────────────────────────────────
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

def representative_dataset():
    for i in range(min(500, len(X_scaled))):
        sample = X_scaled[i].astype(np.float32).reshape(1, 8)
        yield [sample]

converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type  = tf.float32  # keep float input for ESP32 ease
converter.inference_output_type = tf.float32  # keep float output

tflite_model = converter.convert()

print(f"TFLite model size : {len(tflite_model):,} bytes "
      f"({len(tflite_model)/1024:.1f} KB)")

# Save .tflite file
with open('heart_model.tflite', 'wb') as f:
    f.write(tflite_model)
print("heart_model.tflite saved ✓")

# ── Verify TFLite model gives same results as Keras ───────────
interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print(f"\nTFLite input  : {input_details[0]['shape']} "
      f"dtype={input_details[0]['dtype']}")
print(f"TFLite output : {output_details[0]['shape']} "
      f"dtype={output_details[0]['dtype']}")

# Run 10 test samples through both models and compare
print("\nKeras vs TFLite reconstruction error comparison:")
print(f"{'Sample':>8} {'Keras MSE':>12} {'TFLite MSE':>12} {'Match':>8}")

for i in range(10):
    sample = X_scaled[i].astype(np.float32).reshape(1, 8)

    # Keras prediction
    keras_out  = model.predict(sample, verbose=0)
    keras_mse  = float(np.mean(np.square(sample - keras_out)))

    # TFLite prediction
    interpreter.set_tensor(input_details[0]['index'], sample)
    interpreter.invoke()
    tflite_out = interpreter.get_tensor(output_details[0]['index'])
    tflite_mse = float(np.mean(np.square(sample - tflite_out)))

    match = "OK" if abs(keras_mse - tflite_mse) < 0.01 else "DIFF"
    print(f"{i:>8} {keras_mse:>12.6f} {tflite_mse:>12.6f} {match:>8}")

# ── Convert to C header array for ESP32 ──────────────────────
print("\nGenerating model.h for ESP32...")

c_array = ', '.join([f'0x{b:02x}' for b in tflite_model])

header = f"""// Auto-generated by step4_convert_tflite.py
// Model: Heart Rate Anomaly Autoencoder
// Size : {len(tflite_model)} bytes ({len(tflite_model)/1024:.1f} KB)
// Input: 8 float32 features (normalized)
// Output: 8 float32 reconstructed features
// Anomaly threshold: {threshold:.6f}

#ifndef HEART_MODEL_H
#define HEART_MODEL_H

const unsigned int heart_model_len = {len(tflite_model)};
const unsigned char heart_model_data[] = {{
  {c_array}
}};

// Scaler parameters — apply these BEFORE feeding to model
// normalized = (raw - mean) / scale
const float scaler_mean[8]  = {{{', '.join([f'{v:.6f}f' for v in scaler_mean])}}};
const float scaler_scale[8] = {{{', '.join([f'{v:.6f}f' for v in scaler_scale])}}};

// Anomaly detection threshold
// If reconstruction MSE > this value → anomaly detected
const float anomaly_threshold = {threshold:.6f}f;

// Feature index reference:
// [0] hr_zscore        [1] hr_std
// [2] rmssd            [3] activity_code
// [4] accel_mean       [5] accel_std
// [6] hr_delta         [7] activity_hr_ratio

#endif // HEART_MODEL_H
"""

with open('model.h', 'w', encoding='utf-8') as f:
    f.write(header)

print("model.h saved ✓")
print(f"\nContents of model.h header:")
print(f"  Model array size : {len(tflite_model)} bytes")
print(f"  Scaler means     : {scaler_mean.round(4)}")
print(f"  Scaler scales    : {scaler_scale.round(4)}")
print(f"  Threshold        : {threshold:.6f}")

print("\n" + "="*50)
print("Step 4 complete ✓")
print("Files ready for ESP32:")
print("  heart_model.tflite  — for testing")
print("  model.h             — copy into Arduino project")
print("="*50)
